# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

jobs:
- job: "MenuCycleTests"
  timeoutInMinutes: 180

  pool:
    name: Default
    # demands: agent.name -equals SOF-MBP-044
    vmImage: 'windows-latest'

  variables:
    solution: '**/*.sln'
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Chrome'
    
  steps:
  - task: NuGetToolInstaller@1

  - task: NuGetCommand@2
    inputs:
      command: 'restore'
      feedsToUse: config
      restoreSolution: '$(solution)'

  - task: VSBuild@1
    inputs:
      solution: '$(solution)'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'

  - task: VSTest@2
    timeoutInMinutes: 180
    inputs:
      testSelector: 'testAssemblies'
      testAssemblyVer2: '**\*Tests.dll'
      searchFolder: '$(System.DefaultWorkingDirectory)'
      testFiltercriteria: 'TestCategory=TC27777'
      uiTests: true
      configuration: 'Chrome'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'NUnit'
      testResultsFiles: '**/TEST-*.xml'
      mergeTestResults: true