//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuCycleData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportLog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ImportLog()
        {
            this.ImportGroupLocations = new HashSet<ImportGroupLocation>();
        }
    
        public long ImportLogId { get; set; }
        public string ImportType { get; set; }
        public System.DateTime ImportDate { get; set; }
        public long CustomerId { get; set; }
        public int ImportStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImportGroupLocation> ImportGroupLocations { get; set; }
    }
}
