//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuCycleData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MealPeriod
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MealPeriod()
        {
            this.MenuCycleItems = new HashSet<MenuCycleItem>();
        }
    
        public long MealPeriodId { get; set; }
        public System.Guid ExternalId { get; set; }
        public string Name { get; set; }
        public long CustomerId { get; set; }
        public System.DateTime DateCreatedUtc { get; set; }
        public string CreatedByExternalId { get; set; }
        public System.DateTime DateUpdatedUtc { get; set; }
        public string UpdatedByExternalId { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MenuCycleItem> MenuCycleItems { get; set; }
    }
}
