//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuCycleData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MenuServiceSodexoQAIEntities : DbContext
    {
        public MenuServiceSodexoQAIEntities()
            : base("name=MenuServiceSodexoQAIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<GroupLocation> GroupLocations { get; set; }
        public virtual DbSet<GroupMenu> GroupMenus { get; set; }
        public virtual DbSet<GroupRecipe> GroupRecipes { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<GroupUser> GroupUsers { get; set; }
        public virtual DbSet<ImportGroupLocation> ImportGroupLocations { get; set; }
        public virtual DbSet<ImportLog> ImportLogs { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<MealPeriod> MealPeriods { get; set; }
        public virtual DbSet<MenuCycleGroup> MenuCycleGroups { get; set; }
        public virtual DbSet<MenuCycleItem> MenuCycleItems { get; set; }
        public virtual DbSet<MenuCycle> MenuCycles { get; set; }
        public virtual DbSet<MenuRecipe> MenuRecipes { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<Note> Notes { get; set; }
        public virtual DbSet<PostProduction> PostProductions { get; set; }
        public virtual DbSet<RecipeCategory> RecipeCategories { get; set; }
        public virtual DbSet<RecipeIngredientDetail> RecipeIngredientDetails { get; set; }
        public virtual DbSet<RecipeLocationPrice> RecipeLocationPrices { get; set; }
        public virtual DbSet<Recipe> Recipes { get; set; }
        public virtual DbSet<SellPrice> SellPrices { get; set; }
        public virtual DbSet<Tariff> Tariffs { get; set; }
        public virtual DbSet<TaxRate> TaxRates { get; set; }
        public virtual DbSet<UserLocation> UserLocations { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
