//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuCycleData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public long NoteId { get; set; }
        public string Content { get; set; }
        public System.DateTime Date { get; set; }
        public long MenuCycleId { get; set; }
        public System.DateTime DateCreatedUtc { get; set; }
        public string CreatedByExternalId { get; set; }
        public System.DateTime DateUpdatedUtc { get; set; }
        public string UpdatedByExternalId { get; set; }
    
        public virtual MenuCycle MenuCycle { get; set; }
    }
}
