//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuCycleData
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecipeIngredientDetail
    {
        public long RecipeId { get; set; }
        public Nullable<bool> ContainsMilkOrMilkProducts { get; set; }
        public Nullable<bool> ContainsEggOrEggDerivatives { get; set; }
        public Nullable<bool> ContainsCerealsThatContainGluten { get; set; }
        public Nullable<bool> ContainsPeanuts { get; set; }
        public Nullable<bool> ContainsNutsOrNutTrace { get; set; }
        public Nullable<bool> ContainsSesameSeedOrSesameSeedProducts { get; set; }
        public Nullable<bool> ContainsSoya { get; set; }
        public Nullable<bool> ContainsFishOrFishProducts { get; set; }
        public Nullable<bool> ContainsCrustaceans { get; set; }
        public Nullable<bool> ContainsMolluscs { get; set; }
        public Nullable<bool> ContainsMustardOrMustardProducts { get; set; }
        public Nullable<bool> ContainsCeleryOrCeleriacProducts { get; set; }
        public Nullable<bool> ContainsSulphurDioxideOrSulphites { get; set; }
        public Nullable<bool> ContainsLupinFlourOrLupinProducts { get; set; }
        public Nullable<bool> ContainsGlutenOrGlutenProducts { get; set; }
        public Nullable<double> EnergyKJperServing { get; set; }
        public Nullable<double> EnergyKCalPerServing { get; set; }
        public Nullable<double> FatPerServing { get; set; }
        public Nullable<double> SaturatedFatPerServing { get; set; }
        public Nullable<double> SugarPerServing { get; set; }
        public Nullable<double> SaltPerServing { get; set; }
    
        public virtual Recipe Recipe { get; set; }
    }
}
