//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuCycleData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tariff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tariff()
        {
            this.PostProductions = new HashSet<PostProduction>();
            this.SellPrices = new HashSet<SellPrice>();
        }
    
        public long TariffId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime DateCreatedUtc { get; set; }
        public string CreatedByExternalId { get; set; }
        public System.DateTime DateUpdatedUtc { get; set; }
        public string UpdatedByExternalId { get; set; }
        public long Customer_CustomerId { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostProduction> PostProductions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SellPrice> SellPrices { get; set; }
    }
}
